language: generic

env:
  global:
    - PYPI_USER=letmaik

matrix:
  include:
    - os: linux
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

    - os: osx
      # use oldest available image to be as compatible as possible when producing wheels
      # (and one which homebrew still serves with bottles)
      osx_image: xcode7.3 # = OS X 10.11
      # (NumPy 1.7.2 has no macOS wheels)
      env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7.1

    - os: osx
      osx_image: xcode7.3
      env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.8.*

    - os: osx
      osx_image: xcode7.3
      env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.9.*

    - os: osx
      osx_image: xcode7.3
      env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.11.*

    - os: osx
      osx_image: xcode7.3
      env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.14.*

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -e TRAVIS_TAG -e PYPI_USER -e PYPI_PASS -v `pwd`:/io $DOCKER_IMAGE /io/travis/build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis/build_macos.sh; fi

after_success:
  - ls dist/
  - ls build/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/sphinx/html
  on:
    tags: true
    condition: $PYTHON_VERSION = '3.6' && $TRAVIS_OS_NAME == 'osx'